server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          uri: https://github.com/BrunoRFernandes/gft
          search-paths: cliente, gastos     

